CREATE TYPE "Role" AS ENUM ('USER', 'MODERATOR', 'ADMIN');
CREATE TYPE "MembershipTier" AS ENUM ('FREE', 'PREMIUM');
CREATE TYPE "PostType" AS ENUM ('DISCUSSION', 'TIP', 'QUESTION', 'HARVEST', 'SHOWCASE');
CREATE TYPE "PostStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'PINNED', 'LOCKED', 'REMOVED');
CREATE TYPE "NotificationType" AS ENUM ('COMMENT', 'LIKE', 'BADGE', 'SYSTEM', 'MENTION');
CREATE TYPE "AdPlacement" AS ENUM ('HEADER', 'SIDEBAR', 'FEED', 'FOOTER');
